# This workflow is disabled in favor of static.yml
# name: Deploy to GitHub Pages
# 
# on:
#   push:
#     branches: ["main"]
#   workflow_dispatch:
# 
# # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write
# 
# # Allow one concurrent deployment
# concurrency:
#   group: "pages"
#   cancel-in-progress: true
# 
# jobs:
#   # Build job
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       
#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20'
#       
#       - name: Setup Pages
#         uses: actions/configure-pages@v4
#       
#       - name: Install dependencies
#         run: npm install
#       
#       - name: Debug Node & NPM version
#         run: |
#           node --version
#           npm --version
#       
#       - name: Build
#         run: npm run build
#         env:
#           PUBLIC_URL: /mathquest-adventures
#       
#       - name: Debug - List build output
#         run: |
#           echo "Contents of dist directory:"
#           ls -la dist || echo "dist directory not found"
#           
#           # If dist exists, check for size and content
#           if [ -d "dist" ]; then
#             find dist -type f | wc -l
#             du -sh dist
#             find dist -type l | wc -l  # Check for symlinks
#           fi
#       
#       - name: Fix permissions
#         run: |
#           # Make sure there are no symlinks or special files
#           find dist -type l -delete || true
#           
#           # Ensure all files have proper permissions
#           chmod -R 755 dist
#       
#       - name: Upload artifact
#         uses: actions/upload-pages-artifact@v2
#         with:
#           path: dist
# 
#   # Deployment job
#   deploy:
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v3